export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";
export const REMOVE_ITEM="REMOVE_ITEM";
export const EMPTY_CART="EMPTY_CART";
export const LIST_PRODUCTS="LIST_PRODUCTS";
export const SET_PRODUCTS="SET_PRODUCTS";
export const SEARCH_PRODUCTS="SEARCH_PRODUCTS";